### ISSUE TITLE
建议搞个定时任务

### ISSUE THREAD

**Issue by r1172464137** [LucienShui/ikuai-firmware#1]
定时拉取最新的镜像至release ，就像这个一样 https://github.com/tom-snow/wechat-windows-versions

**Comment by LucienShui** [comment]
感谢建议，其实早有这样的想法，只是略懒。已实现。

实现代码：https://github.com/LucienShui/ikuai-firmware/commit/a17bf83413dc1389b1d40c79ba4b6ca580025d48

最新的手动调度结果：https://github.com/LucienShui/ikuai-firmware/commit/800b0e2235666948d9744b1334a451051cbd06ba

每天早上 6:00 调度更新。
