### ISSUE TITLE
话说爱快的插件，试着抓抓看？

### ISSUE THREAD

**Issue by wutaijieing** [LucienShui/ikuai-firmware#4]
比如这个docker插件：
packages.ikuai8.com/docker/3/docker_1.1.18.gen.ikp 
packages.ikuai8.com/docker-bin/3/docker-bin_202102031900.x86_64.ikp
不知道有没有其他的插件，估计有，可能内部使用

**Comment by LucienShui** [comment]
有什么地方可以获取到 latest version 吗？比如：[iKuai version](https://download.ikuai8.com/submit3x/Version_all)，有的话就可以。

**Comment by Score2** [comment]
老实说，意义不大。插件没有公开列表，另外你说的别的插件：
```json
[{
	"name": "pmd",
	"priority": 5,
	"group": "global",
	"type": "daemon",
	"version": "117",
	"ver_method": "pmd -v",
	"ver_cmp": "greater",
	"download": ["https://packages.ikuai8.com/pmd/3/pmd_117.x86_64.ikp", "https://download.ikuai8.com:32016/plugins/others/pmd/3/pmd_117.x86_64.ikp", "http://123.57.179.21/pmd/3/pmd_117.x86_64.ikp"],
	"md5": "d01abb89e6df99b17094f3c8ecf78b66",
	"encryption": "aes-128-cbc",
	"secret_key": "challstr@holly~"
}, {
	"name": "ik_host",
	"priority": 4,
	"group": "global",
	"type": "lib",
	"version": "2022010410",
	"ver_method": "cat /tmp/ikpkg/ik_host/version",
	"ver_cmp": "noequal",
	"download": ["https://packages.ikuai8.com/ik_host/3/ik_host_2022010410.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/ik_host/3/ik_host_2022010410.gen.ikp", "http://123.57.179.21/ik_host/3/ik_host_2022010410.gen.ikp"],
	"md5": "f369080293490112b15778c5fa6d799b",
	"encryption": "aes-128-cbc",
	"secret_key": "jJ9FzkgwUm6bL3dG"
}, {
	"name": "nginx_conf",
	"priority": 10,
	"group": "nginx_conf",
	"type": "script",
	"version": "202105251000",
	"ver_method": "! grep ENTERPRISE=Enterprise /etc/release  >/dev/null && echo 202105251000 ||  cat /tmp/ikpkg/nginx_conf/version 2>/dev/null",
	"ver_cmp": "greater",
	"download": ["https://packages.ikuai8.com/nginx_conf/3/nginx_conf_202105251000.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/nginx_conf/3/nginx_conf_202105251000.gen.ikp", "http://123.57.179.21/nginx_conf/3/nginx_conf_202105251000.gen.ikp"],
	"md5": "e5fe2085bca25820b368daed357cdc02",
	"encryption": "aes-128-cbc",
	"secret_key": "ffba15d0583f089cc073978a5623078e"
}, {
	"name": "router_ip_stats",
	"priority": 14,
	"group": "ipservice",
	"type": "script",
	"version": "2022072214",
	"ver_method": "cat /tmp/ikpkg/router_ip_stats/version",
	"ver_cmp": "noequal",
	"download": ["http://packages.ikuai8.com/ipservice/router_ip_stats/router_ip_stats_2022072214.gen.ikp", "http://pkgdl.ikuai8.com/ipservice/router_ip_stats/router_ip_stats_2022072214.gen.ikp"],
	"md5": "095ddd73b15df77f1decf36eef5ed680",
	"encryption": "aes-128-cbc",
	"secret_key": "nN8yJYfKOEsX5wTifSlvbV1P",
	"monitor_cmd": "/usr/bin/ikluajit /tmp/ikpkg/router_ip_stats/monitor_cmd",
	"monitor_startup_cmd": "echo"
}, {
	"name": "stats_router",
	"priority": 15,
	"group": "global",
	"type": "script",
	"version": "2024041716",
	"ver_method": "cat /tmp/ikpkg/stats_router/version  | cut -d . -f1",
	"ver_cmp": "noequal",
	"download": ["https://packages.ikuai8.com/stats_router/3/stats_router_2024041716.3.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/stats_router/3/stats_router_2024041716.3.gen.ikp", "http://pkgdl.ikuai8.com/stats_router/3/stats_router_2024041716.3.gen.ikp", "http://123.57.179.21/stats_router/3/stats_router_2024041716.3.gen.ikp"],
	"md5": "c938c7538b43a89b73203d582979fb3e",
	"encryption": "aes-128-cbc",
	"secret_key": "sahN7vaiMee9BeeTh1Faigie",
	"monitor_cmd": "ikluajit /tmp/ikpkg/stats_router/monitor_cmd",
	"monitor_startup_cmd": "echo"
}, {
	"name": "firewall",
	"priority": 50,
	"group": "firewall",
	"type": "daemon",
	"version": "202405271443",
	"ver_method": "[[ -f /usr/ikuai/function/ik_firewall ]] && cat /etc/log/firewall/version || echo 0",
	"ver_cmp": "noequal",
	"download": ["http://packages.ikuai8.com/firewall/3/firewall_202405271443.x86_64.ikp"],
	"md5": "64a7f62cf1bf990f42e465aa88538c00",
	"encryption": "aes-128-cbc",
	"secret_key": "e2e840c0ea4abd8af71f1a67a553bbe6",
	"monitor_cmd": "pidof firewall_server"
}, {
	"name": "shell",
	"priority": 15,
	"group": "global",
	"type": "script",
	"version": "202306081801",
	"ver_method": "cat /tmp/ikpkg/shell/version",
	"ver_cmp": "noequal",
	"download": ["http://packages.ikuai8.com/shell/3/shell_202306081801.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/shell/3/shell_202306081801.gen.ikp", "http://pkgdl.ikuai8.com/shell/3/shell_202306081801.gen.ikp", "http://123.57.179.21/shell/3/shell_202306081801.gen.ikp"],
	"md5": "c072b8b2130aaf4609a9d84f3d7fc15c",
	"encryption": "aes-128-cbc",
	"secret_key": "70946f9965a3c140b28e36a82ed148b"
}, {
	"name": "docker-bin",
	"priority": 20,
	"group": "docker-bin",
	"type": "daemon",
	"version": "202102031900",
	"ver_method": "cat /tmp/ikpkg/docker-bin/version",
	"ver_cmp": "noequal",
	"download": ["http://packages.ikuai8.com/docker-bin/3/docker-bin_202102031900.x86_64.ikp", "https://download.ikuai8.com:32016/plugins/others/docker-bin/3/docker-bin_202102031900.x86_64.ikp", "http://pkgdl.ikuai8.com/docker-bin/3/docker-bin_202102031900.x86_64.ikp"],
	"md5": "dc7f031c55b0ee8012cb753d808f64fb",
	"encryption": "aes-128-cbc",
	"secret_key": "354a738f7b2756a848f3b8de541ec58",
	"minimum_size": 69632,
	"timeout_per_request": 600
}, {
	"name": "pre_cdn_stats",
	"priority": 20,
	"group": "global",
	"type": "daemon",
	"version": "1.0.6",
	"ver_method": "cat /tmp/ikpkg/pre_cdn_stats/version",
	"ver_cmp": "noequal",
	"download": ["http://packages.ikuai8.com/pre_cdn_stats/3/pre_cdn_stats_1.0.6.x86_64.ikp"],
	"md5": "a8719b52b13cc91744cc1eb7485e5845",
	"encryption": "aes-128-cbc",
	"secret_key": "e2e840c0ea4abd8af71f1a67a553bbe6"
}, {
	"name": "docker",
	"priority": 50,
	"group": "docker",
	"type": "app",
	"version": "1.1.16",
	"ver_method": "cat /tmp/ikpkg/docker/version",
	"ver_cmp": "noequal",
	"download": ["http://packages.ikuai8.com/docker/3/docker_1.1.16.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/docker/3/docker_1.1.16.gen.ikp", "http://pkgdl.ikuai8.com/docker/3/docker_1.1.16.gen.ikp"],
	"md5": "66933941ae8e7d5ae56a6b3c5f902842",
	"encryption": "aes-128-cbc",
	"secret_key": "354a738f7b2756a848f3b8de541ec57"
}, {
	"name": "netboard",
	"priority": 50,
	"group": "global",
	"type": "script",
	"version": "202107161330",
	"ver_method": "! grep ENTERPRISE=Enterprise /etc/release  >/dev/null && echo 202107161330 ||  cat /tmp/ikpkg/netboard/version 2>/dev/null",
	"ver_cmp": "noequal",
	"download": ["https://packages.ikuai8.com/netboard/3/netboard_202107161330.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/netboard/3/netboard_202107161330.gen.ikp", "http://123.57.179.21/netboard/3/netboard_202107161330.gen.ikp"],
	"md5": "4f90d9720cbc81751cb6c569cbfa5919",
	"encryption": "aes-128-cbc",
	"secret_key": "599eba19aa93a929cb8589f148b8a6c4"
}]
```

**Comment by LucienShui** [comment]
@wutaijieing 如果没有公开的链接的话，不太好在 GitHub Actions 里实现自动抓取，先关了哈。

**Comment by wutaijieing** [comment]
> 老实说，意义不大。官方插件没有公开列表，另外可以自行封装插件，但是爱快环境想开发一个插件，难度很高。 另外你说的别的插件：
> 
> ```json
> [{
> 	"name": "pmd",
> 	"priority": 5,
> 	"group": "global",
> 	"type": "daemon",
> 	"version": "117",
> 	"ver_method": "pmd -v",
> 	"ver_cmp": "greater",
> 	"download": ["https://packages.ikuai8.com/pmd/3/pmd_117.x86_64.ikp", "https://download.ikuai8.com:32016/plugins/others/pmd/3/pmd_117.x86_64.ikp", "http://123.57.179.21/pmd/3/pmd_117.x86_64.ikp"],
> 	"md5": "d01abb89e6df99b17094f3c8ecf78b66",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "challstr@holly~"
> }, {
> 	"name": "ik_host",
> 	"priority": 4,
> 	"group": "global",
> 	"type": "lib",
> 	"version": "2022010410",
> 	"ver_method": "cat /tmp/ikpkg/ik_host/version",
> 	"ver_cmp": "noequal",
> 	"download": ["https://packages.ikuai8.com/ik_host/3/ik_host_2022010410.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/ik_host/3/ik_host_2022010410.gen.ikp", "http://123.57.179.21/ik_host/3/ik_host_2022010410.gen.ikp"],
> 	"md5": "f369080293490112b15778c5fa6d799b",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "jJ9FzkgwUm6bL3dG"
> }, {
> 	"name": "nginx_conf",
> 	"priority": 10,
> 	"group": "nginx_conf",
> 	"type": "script",
> 	"version": "202105251000",
> 	"ver_method": "! grep ENTERPRISE=Enterprise /etc/release  >/dev/null && echo 202105251000 ||  cat /tmp/ikpkg/nginx_conf/version 2>/dev/null",
> 	"ver_cmp": "greater",
> 	"download": ["https://packages.ikuai8.com/nginx_conf/3/nginx_conf_202105251000.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/nginx_conf/3/nginx_conf_202105251000.gen.ikp", "http://123.57.179.21/nginx_conf/3/nginx_conf_202105251000.gen.ikp"],
> 	"md5": "e5fe2085bca25820b368daed357cdc02",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "ffba15d0583f089cc073978a5623078e"
> }, {
> 	"name": "router_ip_stats",
> 	"priority": 14,
> 	"group": "ipservice",
> 	"type": "script",
> 	"version": "2022072214",
> 	"ver_method": "cat /tmp/ikpkg/router_ip_stats/version",
> 	"ver_cmp": "noequal",
> 	"download": ["http://packages.ikuai8.com/ipservice/router_ip_stats/router_ip_stats_2022072214.gen.ikp", "http://pkgdl.ikuai8.com/ipservice/router_ip_stats/router_ip_stats_2022072214.gen.ikp"],
> 	"md5": "095ddd73b15df77f1decf36eef5ed680",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "nN8yJYfKOEsX5wTifSlvbV1P",
> 	"monitor_cmd": "/usr/bin/ikluajit /tmp/ikpkg/router_ip_stats/monitor_cmd",
> 	"monitor_startup_cmd": "echo"
> }, {
> 	"name": "stats_router",
> 	"priority": 15,
> 	"group": "global",
> 	"type": "script",
> 	"version": "2024041716",
> 	"ver_method": "cat /tmp/ikpkg/stats_router/version  | cut -d . -f1",
> 	"ver_cmp": "noequal",
> 	"download": ["https://packages.ikuai8.com/stats_router/3/stats_router_2024041716.3.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/stats_router/3/stats_router_2024041716.3.gen.ikp", "http://pkgdl.ikuai8.com/stats_router/3/stats_router_2024041716.3.gen.ikp", "http://123.57.179.21/stats_router/3/stats_router_2024041716.3.gen.ikp"],
> 	"md5": "c938c7538b43a89b73203d582979fb3e",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "sahN7vaiMee9BeeTh1Faigie",
> 	"monitor_cmd": "ikluajit /tmp/ikpkg/stats_router/monitor_cmd",
> 	"monitor_startup_cmd": "echo"
> }, {
> 	"name": "firewall",
> 	"priority": 50,
> 	"group": "firewall",
> 	"type": "daemon",
> 	"version": "202405271443",
> 	"ver_method": "[[ -f /usr/ikuai/function/ik_firewall ]] && cat /etc/log/firewall/version || echo 0",
> 	"ver_cmp": "noequal",
> 	"download": ["http://packages.ikuai8.com/firewall/3/firewall_202405271443.x86_64.ikp"],
> 	"md5": "64a7f62cf1bf990f42e465aa88538c00",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "e2e840c0ea4abd8af71f1a67a553bbe6",
> 	"monitor_cmd": "pidof firewall_server"
> }, {
> 	"name": "shell",
> 	"priority": 15,
> 	"group": "global",
> 	"type": "script",
> 	"version": "202306081801",
> 	"ver_method": "cat /tmp/ikpkg/shell/version",
> 	"ver_cmp": "noequal",
> 	"download": ["http://packages.ikuai8.com/shell/3/shell_202306081801.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/shell/3/shell_202306081801.gen.ikp", "http://pkgdl.ikuai8.com/shell/3/shell_202306081801.gen.ikp", "http://123.57.179.21/shell/3/shell_202306081801.gen.ikp"],
> 	"md5": "c072b8b2130aaf4609a9d84f3d7fc15c",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "70946f9965a3c140b28e36a82ed148b"
> }, {
> 	"name": "docker-bin",
> 	"priority": 20,
> 	"group": "docker-bin",
> 	"type": "daemon",
> 	"version": "202102031900",
> 	"ver_method": "cat /tmp/ikpkg/docker-bin/version",
> 	"ver_cmp": "noequal",
> 	"download": ["http://packages.ikuai8.com/docker-bin/3/docker-bin_202102031900.x86_64.ikp", "https://download.ikuai8.com:32016/plugins/others/docker-bin/3/docker-bin_202102031900.x86_64.ikp", "http://pkgdl.ikuai8.com/docker-bin/3/docker-bin_202102031900.x86_64.ikp"],
> 	"md5": "dc7f031c55b0ee8012cb753d808f64fb",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "354a738f7b2756a848f3b8de541ec58",
> 	"minimum_size": 69632,
> 	"timeout_per_request": 600
> }, {
> 	"name": "pre_cdn_stats",
> 	"priority": 20,
> 	"group": "global",
> 	"type": "daemon",
> 	"version": "1.0.6",
> 	"ver_method": "cat /tmp/ikpkg/pre_cdn_stats/version",
> 	"ver_cmp": "noequal",
> 	"download": ["http://packages.ikuai8.com/pre_cdn_stats/3/pre_cdn_stats_1.0.6.x86_64.ikp"],
> 	"md5": "a8719b52b13cc91744cc1eb7485e5845",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "e2e840c0ea4abd8af71f1a67a553bbe6"
> }, {
> 	"name": "docker",
> 	"priority": 50,
> 	"group": "docker",
> 	"type": "app",
> 	"version": "1.1.16",
> 	"ver_method": "cat /tmp/ikpkg/docker/version",
> 	"ver_cmp": "noequal",
> 	"download": ["http://packages.ikuai8.com/docker/3/docker_1.1.16.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/docker/3/docker_1.1.16.gen.ikp", "http://pkgdl.ikuai8.com/docker/3/docker_1.1.16.gen.ikp"],
> 	"md5": "66933941ae8e7d5ae56a6b3c5f902842",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "354a738f7b2756a848f3b8de541ec57"
> }, {
> 	"name": "netboard",
> 	"priority": 50,
> 	"group": "global",
> 	"type": "script",
> 	"version": "202107161330",
> 	"ver_method": "! grep ENTERPRISE=Enterprise /etc/release  >/dev/null && echo 202107161330 ||  cat /tmp/ikpkg/netboard/version 2>/dev/null",
> 	"ver_cmp": "noequal",
> 	"download": ["https://packages.ikuai8.com/netboard/3/netboard_202107161330.gen.ikp", "https://download.ikuai8.com:32016/plugins/others/netboard/3/netboard_202107161330.gen.ikp", "http://123.57.179.21/netboard/3/netboard_202107161330.gen.ikp"],
> 	"md5": "4f90d9720cbc81751cb6c569cbfa5919",
> 	"encryption": "aes-128-cbc",
> 	"secret_key": "599eba19aa93a929cb8589f148b8a6c4"
> }]
> ```


那想请教下，可以在没有ssh的情况下自定义降级插件吗？
