### ISSUE TITLE
免费版升级企业版，提示“错误：无法识别这个文件”

### ISSUE THREAD

**Issue by uwang** [LucienShui/ikuai-firmware#6]
![image](https://github.com/user-attachments/assets/7f64b222-495b-492a-ab29-3a5bf5702021)

自组x86吋间，请问有办法安装么？

最近流传出来一个企业版（社区版） 3.7.16 的 bin，可以正常安装。升级这里下载的企业版就是这个提示。

**Comment by Score2** [comment]
本仓库的作用仅仅只是拼接出官方固件的下载链接，而固件也同样来自于官方。官方本身就设定不允许企业版和免费版互刷。

而我的提交代码的初衷也并非是为了让免费版能够直接升级到企业版，请参见#2

此外，爱快的固件为商业固件，对其破解还会存在法律风险。

**Comment by uwang** [comment]
感谢回答
